version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./laravel:/var/www/
      - ./nginx/conf.d:/etc/nginx/conf.d/
      # - ./nginx/logs:/var/log/nginx/
    ports:
      - "80:80"
    tty:  true
    restart: unless-stopped
    container_name: nginx_cpro
    depends_on:
      - lar8cpro

  lar8cpro:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CSP_DISTR: "sources/linux-amd64_deb.tgz"
        CADES_DISTR: "sources/cades-linux-amd64.tar.gz"
        PHP_PATCH: "sources/php7_support.patch"
        PHP_URL: "https://www.php.net/distributions/php-7.4.3.tar.gz"
        TEST_CA_DIR: "certificates/4BC6DC14D97010C41A26E058AD851F81C842415A.cer"
    tty:  true
    user: 1000:1000
    restart: unless-stopped
    volumes:
      - ./laravel:/var/www
    container_name: lar8cpro
